# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MySQL-Sandbox
version:      3.0.04
version_from: lib/MySQL/Sandbox.pm
installdirs:  site
requires:
    File::Find:                    1.1
    Socket:                        1.7

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
